// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rezio.Api.Persistence;

#nullable disable

namespace Rezio.Api.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260717090002_InitialMarketData")]
    partial class InitialMarketData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rezio.Api.Persistence.MarketDataRecord", b =>
                {
                    b.Property<string>("MarketId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DemandDriversJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DemandScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastWrittenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("OccupancyRate")
                        .HasColumnType("double precision");

                    b.HasKey("MarketId", "Date");

                    b.ToTable("market_data", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
